//! Windows resources shared by the `purgekit` and `purgekit-helper` build
//! scripts (`#[path]`-included): the app icon and a VERSIONINFO block whose
//! version comes from Cargo. Explorer, Task Manager and the UAC prompt read
//! these from the .exe.

use std::path::Path;

pub struct Exe<'a> {
    /// Shown in Task Manager and in the UAC prompt.
    pub description: &'a str,
    pub internal_name: &'a str,
    pub original_filename: &'a str,
}

/// Writes `purgekit.rc` into `OUT_DIR` and links it into the binary.
pub fn embed(exe: &Exe) {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let icon = Path::new(&manifest_dir).join("../../ui/purgekit.ico");
    let icon = icon.canonicalize().expect("ui/purgekit.ico");
    // rc.exe and windres both accept forward slashes; `\\?\` is not accepted.
    let icon = icon
        .to_string_lossy()
        .trim_start_matches(r"\\?\")
        .replace('\\', "/");

    let num = |key: &str| -> u16 {
        std::env::var(key)
            .expect(key)
            .parse()
            .expect("numeric version part")
    };
    let (major, minor, patch) = (
        num("CARGO_PKG_VERSION_MAJOR"),
        num("CARGO_PKG_VERSION_MINOR"),
        num("CARGO_PKG_VERSION_PATCH"),
    );
    let version = std::env::var("CARGO_PKG_VERSION").expect("CARGO_PKG_VERSION");

    // Numeric constants instead of <winver.h>, so no SDK include path is needed:
    // FILEOS 0x40004 = VOS_NT_WINDOWS32, FILETYPE 0x1 = VFT_APP.
    let rc = format!(
        r#"// Generated by apps/winres.rs. The lowest icon ID is the one Windows shows.
1 ICON "{icon}"

1 VERSIONINFO
FILEVERSION {major},{minor},{patch},0
PRODUCTVERSION {major},{minor},{patch},0
FILEFLAGSMASK 0x3f
FILEFLAGS 0x0
FILEOS 0x40004
FILETYPE 0x1
FILESUBTYPE 0x0
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904b0"
        BEGIN
            VALUE "CompanyName", "PurgeKit"
            VALUE "FileDescription", "{description}"
            VALUE "FileVersion", "{version}"
            VALUE "InternalName", "{internal}"
            VALUE "LegalCopyright", "Copyright (c) 2026 the PurgeKit contributors. MIT License."
            VALUE "OriginalFilename", "{original}"
            VALUE "ProductName", "PurgeKit"
            VALUE "ProductVersion", "{version}"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x409, 1200
    END
END
"#,
        description = exe.description,
        internal = exe.internal_name,
        original = exe.original_filename,
    );
    let rc_path = Path::new(&out_dir).join("purgekit.rc");
    std::fs::write(&rc_path, rc).expect("write purgekit.rc");
    embed_resource::compile(&rc_path, embed_resource::NONE)
        .manifest_required()
        .expect("unable to embed the icon and version resources");
    println!("cargo:rerun-if-changed=../../ui/purgekit.ico");
    println!("cargo:rerun-if-changed=../winres.rs");
}
